version: "3"

services:
  appbot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: >
      "nodemon"
  mysql:
    image: mysql:8.0.33
    restart: always
    ports:
      - "13306:3306"
    volumes:
      - ./.data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: clanbattlebot
      MYSQL_PASSWORD: clanbattlebot
      MYSQL_DATABASE: clanbattle
